version: '2'
networks:
  icinga:
    name: icinga
services:
  icinga_mariadb:
    image: mariadb:focal
    container_name: icinga_mariadb
    restart: unless-stopped
    networks:
      - icinga
    hostname: icinga-mariadb
    env_file:
      - example-grafana.env
    volumes:
      - /data/var/lib/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 9
      start_period: 5s
  icinga_influxdb:
    image: influxdb:2.1
    container_name: icinga_influxdb
    restart: unless-stopped
    networks:
      - icinga
    hostname: icinga-influxdb
    env_file:
      - example-grafana.env
    volumes:
      - /data/var/lib/influxdb2:/var/lib/influxdb2
      - /data/etc/influxdb2:/etc/influxdb2
  icinga_grafana:
    image: grafana/grafana-oss:8.4.4
    container_name: icinga_grafana
    restart: unless-stopped
    networks:
      - icinga
    hostname: icinga-grafana
    env_file:
      - example-grafana.env
    ports:
      - "3000:3000"
    depends_on:
      icinga_influxdb:
        condition: service_started
  icinga_icinga2:
    image: deltabg/icinga2
    container_name: icinga_icinga2
    restart: unless-stopped
    networks:
      - icinga
    hostname: icinga-icinga2
    env_file:
      - example-grafana.env
    volumes:
      - /data/etc/icinga2:/etc/icinga2
      - /data/var/lib/icinga2:/var/lib/icinga2
      - /data/var/log/icinga2:/var/log/icinga2
      - /data/usr/lib/nagios/plugins:/usr/lib/nagios/plugins
    ports:
      - "5665:5665"
    privileged: true
    depends_on:
      icinga_mariadb:
        condition: service_healthy
      icinga_influxdb:
        condition: service_started
      icinga_grafana:
        condition: service_started
  icinga_icingaweb2:
    image: deltabg/icingaweb2
    container_name: icinga_icingaweb2
    restart: unless-stopped
    networks:
      - icinga
    hostname: icinga-icingaweb2
    env_file:
      - example-grafana.env
    volumes:
      - /data/etc/icingaweb2:/etc/icingaweb2
      - /data/var/log/icingaweb2:/var/log/icingaweb2
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      icinga_mariadb:
        condition: service_healthy
      icinga_influxdb:
        condition: service_started
      icinga_grafana:
        condition: service_started
      icinga_icinga2:
        condition: service_healthy
